apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubernetes-demo-app
  namespace: demo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: kubernetes-demo-app
  template:
    metadata:
      labels:
        app: kubernetes-demo-app
    spec:
      containers:
        - name: kubernetes-demo-app
          image: ${DOCKER_USERNAME}/kubernetes-demo-app:latest
          ports:
            - containerPort: 3000
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
          livenessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 5
