apiVersion: v1
kind: Service
metadata:
  name: kubernetes-demo-service
  namespace: demo
spec:
  type: NodePort
  selector:
    app: kubernetes-demo-app
  ports:
    - port: 80
      targetPort: 3000
      nodePort: 30007
